export const TOTAL_PRODUCTS_SUCCESS = "TOTAL_PRODUCTS_SUCCESS";
export const TOTAL_PRODUCTS_REQUEST = "TOTAL_PRODUCTS_REQUEST";
export const TOTAL_PRODUCTS_FAIL = "TOTAL_PRODUCTS_FAIL";

export const RANDOM_PRODUCT_SUCCESS = "RANDOM_PRODUCT_SUCCESS";
export const RANDOM_PRODUCT_REQUEST = "RANDOM_PRODUCT_REQUEST";
export const RANDOM_PRODUCT_FAIL = "RANDOM_PRODUCT_FAIL";
